version: "2"
services:
  front:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address: 172.20.0.2

  back:
    container_name: back
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    networks:
      app_net:
        ipv4_address: 172.20.0.3

networks:
  app_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1